# Generated by Django 5.0.6 on 2025-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="medications",
            field=models.TextField(),
        ),
    ]
